version: "3.9"
services:
  db:
    image: "postgres:17"
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER?:DB_USER not set}"
      POSTGRES_PASSWORD: "${DB_PWD?:DB_PWD not set}"
    volumes:
      - ./db:/var/lib/postgresql/data
  app:
    build:
      context: .
      args:
        SECRET_KEY: "${SECRET_KEY?:SECRET_KEY not set}"
    image: ku-polls
    environment:
      SECRET_KEY: "${SECRET_KEY?:SECRET_KEY not set}"
      DATABASE_USERNAME: "${DB_USER?:DB_USER not set}"
      DATABASE_PASSWORD: "${DB_PWD?:DB_PWD not set}"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    links:
      - db
    depends_on:
      - db
    ports:
      - '8000:8000'
